# Generated by Django 5.0.3 on 2024-03-25 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Périmètre',
            fields=[
                ('id_périmètre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visualisation',
            fields=[
                ('id_visualisation', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('visualisation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prévision_perimetre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('prévision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('périmètre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.périmètre')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier_mansuelle',
            fields=[
                ('id_fichier', models.AutoField(primary_key=True, serialize=False)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('stock_ini', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Apport_consommation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consomme', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preleve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pertes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expedie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laivraison', models.DecimalField(decimal_places=2, max_digits=10)),
                ('densite', models.DecimalField(decimal_places=1, max_digits=3)),
                ('périmètre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.périmètre')),
            ],
        ),
        migrations.AddField(
            model_name='périmètre',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.region'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commentaire', models.TextField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.utilisateur')),
                ('visualisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.visualisation')),
            ],
            options={
                'unique_together': {('utilisateur', 'visualisation')},
            },
        ),
    ]
