# Generated by Django 5.0.3 on 2024-03-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='Apport_consommation',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='consomme',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='densite',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='expedie',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='laivraison',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='pertes',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='preleve',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='produit',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='stock_ini',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
