# Generated by Django 5.0.3 on 2024-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_fichier_mansuelle_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='SONATRACH12', max_length=128),
        ),
    ]
