# Generated by Django 5.0.3 on 2024-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_utilisateur_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier_mansuelle',
            name='produit',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
