# Generated by Django 5.0.3 on 2024-05-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_fichier_mansuelle_produit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fichier_mansuelle',
            unique_together={('mois', 'annee', 'périmètre')},
        ),
    ]
