# Generated by Django 5.0.3 on 2024-05-26 18:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_fichier_mansuelle_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualisation',
            name='visualisation',
        ),
        migrations.AddField(
            model_name='visualisation',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.region'),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.utilisateur'),
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
